version: '3.8'

services:
  app:
    build: ./app
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: "mongodb://mongo_db:27017/mydatabase"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
